services:
  postgres:
    image: postgres:16-alpine
    container_name: ticketbox-postgres
    environment:
      POSTGRES_USER: ticketbox
      POSTGRES_PASSWORD: ticketbox
      POSTGRES_DB: ticketbox
    command: postgres -c max_connections=500
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ticketbox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  k6:
    image: grafana/k6:latest
    container_name: ticketbox-k6
    profiles: [ "test" ]
    env_file:
      - ./tests/.env
    volumes:
      - ./tests:/tests
    environment:
      - BASE_URL=http://host.docker.internal:3000/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: [ "k6" ]

volumes:
  postgres_data:
  redis_data:
