export const AUDIT_ACTIONS = {
  RETRY_NOTIFICATION: "RETRY_NOTIFICATION",
  PAYMENT_WEBHOOK_SUCCEEDED: "PAYMENT_WEBHOOK_SUCCEEDED",
  PAYMENT_WEBHOOK_FAILED: "PAYMENT_WEBHOOK_FAILED",
  TICKET_ISSUED: "TICKET_ISSUED",
  TICKET_VOIDED: "TICKET_VOIDED",
  GUEST_IMPORT_TRIGGERED: "GUEST_IMPORT_TRIGGERED",
  CONCERT_AUTO_PUBLISHED: "CONCERT_AUTO_PUBLISHED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ENTITY_TYPES = {
  NOTIFICATION: "notification",
  PAYMENT: "payment",
  TICKET: "ticket",
  GUEST_IMPORT_JOB: "guest_import_job",
  CONCERT: "concert",
} as const;

export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];
